// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cox_reg_sparse_parallel
List cox_reg_sparse_parallel(List covrowlist_in, DoubleVector beta_in, IntegerVector id_in, DoubleVector coval_in, DoubleVector weights_in, IntegerVector timein_in, IntegerVector timeout_in, IntegerVector Outcomes_in, IntegerVector OutcomeTotals_in, IntegerVector OutcomeTotalTimes_in, int nvar, double lambda, int MSTEP_MAX_ITER, double MAX_EPS, int threadn);
RcppExport SEXP _coxsparse_cox_reg_sparse_parallel(SEXP covrowlist_inSEXP, SEXP beta_inSEXP, SEXP id_inSEXP, SEXP coval_inSEXP, SEXP weights_inSEXP, SEXP timein_inSEXP, SEXP timeout_inSEXP, SEXP Outcomes_inSEXP, SEXP OutcomeTotals_inSEXP, SEXP OutcomeTotalTimes_inSEXP, SEXP nvarSEXP, SEXP lambdaSEXP, SEXP MSTEP_MAX_ITERSEXP, SEXP MAX_EPSSEXP, SEXP threadnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type covrowlist_in(covrowlist_inSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type beta_in(beta_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type id_in(id_inSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type coval_in(coval_inSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type weights_in(weights_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type timein_in(timein_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type timeout_in(timeout_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Outcomes_in(Outcomes_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type OutcomeTotals_in(OutcomeTotals_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type OutcomeTotalTimes_in(OutcomeTotalTimes_inSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type MSTEP_MAX_ITER(MSTEP_MAX_ITERSEXP);
    Rcpp::traits::input_parameter< double >::type MAX_EPS(MAX_EPSSEXP);
    Rcpp::traits::input_parameter< int >::type threadn(threadnSEXP);
    rcpp_result_gen = Rcpp::wrap(cox_reg_sparse_parallel(covrowlist_in, beta_in, id_in, coval_in, weights_in, timein_in, timeout_in, Outcomes_in, OutcomeTotals_in, OutcomeTotalTimes_in, nvar, lambda, MSTEP_MAX_ITER, MAX_EPS, threadn));
    return rcpp_result_gen;
END_RCPP
}
// profile_ci
NumericMatrix profile_ci(List covrowlist_in, DoubleVector beta_in, IntegerVector id_in, DoubleVector coval_in, DoubleVector weights_in, IntegerVector timein_in, IntegerVector timeout_in, IntegerVector Outcomes_in, IntegerVector OutcomeTotals_in, IntegerVector OutcomeTotalTimes_in, double lambda, int nvar, int MSTEP_MAX_ITER, int decimals, double confint_width, int threadn);
RcppExport SEXP _coxsparse_profile_ci(SEXP covrowlist_inSEXP, SEXP beta_inSEXP, SEXP id_inSEXP, SEXP coval_inSEXP, SEXP weights_inSEXP, SEXP timein_inSEXP, SEXP timeout_inSEXP, SEXP Outcomes_inSEXP, SEXP OutcomeTotals_inSEXP, SEXP OutcomeTotalTimes_inSEXP, SEXP lambdaSEXP, SEXP nvarSEXP, SEXP MSTEP_MAX_ITERSEXP, SEXP decimalsSEXP, SEXP confint_widthSEXP, SEXP threadnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type covrowlist_in(covrowlist_inSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type beta_in(beta_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type id_in(id_inSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type coval_in(coval_inSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type weights_in(weights_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type timein_in(timein_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type timeout_in(timeout_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Outcomes_in(Outcomes_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type OutcomeTotals_in(OutcomeTotals_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type OutcomeTotalTimes_in(OutcomeTotalTimes_inSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< int >::type MSTEP_MAX_ITER(MSTEP_MAX_ITERSEXP);
    Rcpp::traits::input_parameter< int >::type decimals(decimalsSEXP);
    Rcpp::traits::input_parameter< double >::type confint_width(confint_widthSEXP);
    Rcpp::traits::input_parameter< int >::type threadn(threadnSEXP);
    rcpp_result_gen = Rcpp::wrap(profile_ci(covrowlist_in, beta_in, id_in, coval_in, weights_in, timein_in, timeout_in, Outcomes_in, OutcomeTotals_in, OutcomeTotalTimes_in, lambda, nvar, MSTEP_MAX_ITER, decimals, confint_width, threadn));
    return rcpp_result_gen;
END_RCPP
}
// safelog
double safelog(double x);
RcppExport SEXP _coxsparse_safelog(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(safelog(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_coxsparse_cox_reg_sparse_parallel", (DL_FUNC) &_coxsparse_cox_reg_sparse_parallel, 15},
    {"_coxsparse_profile_ci", (DL_FUNC) &_coxsparse_profile_ci, 16},
    {"_coxsparse_safelog", (DL_FUNC) &_coxsparse_safelog, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_coxsparse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
